trigger:
  branches:
    include:
    - shell
    - shell-4
    - releases/*
  paths:
    exclude:
    - README.md
    include:
    - package.json

variables:
- group: API_KEYS


jobs:
- job: Windows_x64
  pool:
    vmImage: VS2017-Win2016
  variables:
    VSCODE_ARCH: x64
    BINTRAY_ARCH: x64
  steps:
  - template: build/azure-pipelines/win32/build-win32-x64-local.yml

