trigger:
- shell

jobs:
- job: Windows
  pool:
    vmImage: VS2017-Win2016
  steps:
  - template: build/azure-pipelines/win32/continuous-build-win32.yml

- job: Linux
  pool:
    name: Default
  #  vmImage: 'Ubuntu-16.04'
  steps:
  - template: build/azure-pipelines/linux/continuous-build-linux.yml

