trigger:
  branches:
    include:
    - light-electron-6
    - releases/*
  paths:
    exclude:
    - README.md
    include:
    - package.json

variables:
- group: API_KEYS

resources:
  containers:
  - container: vscode-x64
    image: joaomoreno/vscode-linux-build-agent:x64
  - container: vscode-ia32
    image: joaomoreno/vscode-linux-build-agent:ia32

jobs:
- job: Windows_ia32
  pool:
    vmImage: VS2017-Win2016
  variables:
    VSCODE_ARCH: ia32
    BINTRAY_ARCH: x86
  steps:
  - template: build/azure-pipelines/win32/build-win32-ia32.yml

