trigger:
  branches:
    include:
    - electron-6
    - light-electron-6
    - releases/*
  paths:
    exclude:
    - README.md
    include:
    - package.json

variables:
- group: API_KEYS

jobs:
- job: Windows_ia32_local
  pool: local-dell-xps15
  variables:
    VSCODE_ARCH: ia32
    BINTRAY_ARCH: x86
  steps:
  - template: build/azure-pipelines/win32/build-win32-local.yml
