trigger:
  branches:
    include:
    - light-electron-6
    - releases/*
  paths:
    exclude:
    - README.md
    include:
    - package.json

variables:
- group: API_KEYS

jobs:
- job: Linux_x64_local_centos7
  pool: Default
  variables:
    VSCODE_ARCH: x64
    BINTRAY_ARCH: x64
    BUID_RPM: 1
    BUILD_DEB: 0
  steps:
  - template: build/azure-pipelines/linux/build-linux-rhel.yml
